apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "5432"
  REDIS_PORT: "6379"
  DB_USERNAME: "$DB_USERNAME"
  DB_HOST: "$DB_HOST"
  DB_DATABASE: "$DB_DATABASE"
  AWS_REGION: "$AWS_REGION"
  AWS_SQS_QUEUE_URL: "$AWS_SQS_QUEUE_URL"
  REDIS_ENDPOINT: "$REDIS_ENDPOINT"
  EKS_CLUSTER_NAME: "$EKS_CLUSTER_NAME"